#!/usr/bin/env python3

import fileinput
import sys

animals = {
    'alligator',
    'anaconda',
    'ant',
    'badger',
    'bass',
    'bat',
    'beaver',
    'bee',
    'beetle',
    'bird',
    'bison',
    'boar',
    'buck',
    'buffalo',
    'bull',
    'calf',
    'camel',
    'carp',
    'cat',
    'cheetah',
    'chicken',
    'chimp',
    'chimpanzee',
    'clam',
    'coral',
    'cow',
    'coyote',
    'crab',
    'crawfish',
    'crayfish',
    'crocodile',
    'crow',
    'deer',
    'doe',
    'dog',
    'dolphin',
    'donkey',
    'dove',
    'drake',
    'duck',
    'eagle',
    'eel',
    'elephant',
    'elk',
    'emu',
    'ewe',
    'fawn',
    'fish',
    'flea',
    'fly',
    'foal',
    'fox',
    'frog',
    'gander',
    'gator',
    'gazelle',
    'gecko',
    'gerbil',
    'giraffe',
    'goat',
    'goose',
    'gorilla',
    'gosling',
    'hamster',
    'hare',
    'hawk',
    'hippo',
    'hog',
    'horse',
    'hyena',
    'ibex',
    'iguana',
    'jaguar',
    'jellyfish',
    'kangaroo',
    'kitten',
    'koala',
    'lamb',
    'leopard',
    'lion',
    'lizard',
    'lobster',
    'lynx',
    'macaw',
    'mare',
    'mole',
    'monkey',
    'moose',
    'moth',
    'mouse',
    'mussel',
    'newt',
    'orang',
    'orangutan',
    'ostrich',
    'otter',
    'owl',
    'ox',
    'oyster',
    'panda',
    'panther',
    'parrot',
    'peacock',
    'pelican',
    'penguin',
    'pig',
    'pigeon',
    'piglet',
    'puma',
    'puppy',
    'rabbit',
    'ram',
    'rat',
    'raven',
    'ray',
    'rhino',
    'roach',
    'salmon',
    'scallop',
    'scorpion',
    'seagull',
    'seal',
    'sealion',
    'shark',
    'shrimp',
    'sloth',
    'snail',
    'snake',
    'sow',
    'sparrow',
    'spider',
    'squid',
    'stag',
    'stallion',
    'starfish',
    'stingray',
    'stork',
    'swan',
    'tick',
    'tiger',
    'toad',
    'tortoise',
    'toucan',
    'trout',
    'tuna',
    'turkey',
    'turtle',
    'urchin',
    'vulture',
    'walrus',
    'warthog',
    'wasp',
    'whale',
    'wolf',
    'worm',
    'zebra',
}
animals = sorted(animals, key=len, reverse=True)

for line in fileinput.input():
    line = line.strip()
    orig = line
    stripped = ''
    found = []

    while line:
        for animal in animals:
            if line.startswith(animal):
                found.append(animal)
                line = line[len(animal):]
                break
        # No animals found.
        else:
            stripped += line[0]
            line = line[1:]

    if found and stripped:
        with open('-'.join(found) + '.txt', 'a') as file:
            file.write(f"{stripped.upper()} + {'/'.join(found)} = {orig}\n")

        #if ''.join(found) + stripped != orig:
        #    print(f"{(''.join(found) + stripped).upper()} [{orig} = {'/'.join(found)}]")
        #if stripped + ''.join(found) != orig:
        #    print(f"{(stripped + ''.join(found)).upper()} [{orig} = {'/'.join(found)}]")
