#!/bin/bash

main() {
    local min_score=30
    if [[ $1 == -m || $1 == --min || $1 == --min_score ]]; then
        min_score=$2
        shift 2
    fi

    local word=$1
    local wordlist="${2:-wordlist.txt}"

    rg "$word" "$wordlist" |
        ./phrases.py --min_score "$min_score" |
        rg -w "$word" |
        sed 's/ //g' |
        uniq |
        rgl "$word"
}

rgl() {
    if [[ -t 1 ]]; then
        rg -p "$@" | less -R
    else
        rg "$@"
    fi
}

main "$@"
