#!/bin/bash

main() {
    local word="$1"
    local wordlist="${2:-wordlist.txt}"

    rg "$word" "$wordlist" |
        ./phrases.py --min 30 |
        rg -w "$word" |
        sed 's/ //g' |
        uniq |
        rgl "$word"
}

rgl() {
    if [[ -t 1 ]]; then
        rg -p "$@" | less -R
    else
        rg "$@"
    fi
}

main "$@"
